version: '3.2'

services:

  influxdb:
    build: influxdb
    env_file: configuracionInfluxGF.env
    ports:
      - '8086:8086' #Puerto base de Influxdb
    volumes:
      - /home/svl/influxdb:/var/lib/influxdb:rw
      

  grafana:
    build: grafana
    env_file: configuracionInfluxGF.env
    links:
      - influxdb
    ports:
      - '3000:3000' #Puerto base de grafana

volumes:
  influxdb:
